project:
  type: book

book:
  title: "testbook"
  author: "Norah Jones"
  date: "4/23/2024"
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - intro.qmd
    - part: Second
      chapters:        
        - summary.qmd
        - references.qmd
  sidebar:
    title: " "
    logo: "content/cce_logo_smalllight.png"

  page-footer: "These lecture notes and tools are licensed under the
  [CC BY-SA 4.0](http://creativecommons.org/licenses/by-sa/4.0/) 
  <img src='https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg' />"

bibliography: references.bib

execute:
  freeze: auto


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    include-after-body:
      text: |
        <script type="application/javascript" src="light-dark.js"></script>
        <script type="application/javascript" src="nav.js"></script>
#  pdf:
#    documentclass: scrreprt



resources: 
  - "content/cce_logo_small.png"