project:
  type: book

book:
  title: "testbook"
  author: "Norah Jones"
  date: "4/23/2024"
  chapters:
    - part: Introduction
      chapters:
        - index.qmd
        - intro.qmd
    - part: Second
      chapters:        
        - summary.qmd
        - references.qmd
  sidebar:
    title: " "
    logo: "content/cce_logo_smalllight.png"

bibliography: references.bib



format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    include-after-body:
      text: |
        <script type="application/javascript" src="light-dark.js"></script>
        <script type="application/javascript" src="nav.js"></script>
#  pdf:
#    documentclass: scrreprt



resources: 
  - "content/cce_logo_small.png"