project:
  type: book

book:
  title: "testbook"
  author: "Norah Jones"
  date: "4/23/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

  sidebar:
    logo: "cce_logo_small.light.png"

bibliography: references.bib



format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    include-after-body:
      text: |
        <script type="application/javascript" src="light-dark.js"></script>
#  pdf:
#    documentclass: scrreprt



resources: 
  - "cce_logo_small.dark.png"